# define a default docker image for all jobs
image: node:8.10

stages:
    - install # install all npm dependencies
    - test    # execute unit tests

npmInstall:
    stage: install
    script:
        - npm install -g firebase-tools
        - cd functions
        - npm install
        - cd ..
    # artifacts describe the result of the stage
    # that can be used in consecutive stages
    artifacts:
        untracked: true

unittesting:
    stage: test
    # use the artifacts of the 'npmInstall' job
    dependencies:
        - npmInstall
    variables:
        ENDPOINT: $ENDPOINT
        ACCESS_KEY: $ACCESS_KEY
    script:
        # install dev-dependency
        - npm install bespoken-tools -g
        - npm test
